<!-- 
*****************
Copying of any part(s) of this website's graphics, design or code is not permitted. Date of Creation: 14th February 2004.
All design, content and images used in this website is protected by the Data Protection Act of 1998 formed in the United Kingdom.
Republishing or distributing any content on these pages without consent from the author is NOT permitted.
*****************
-->