			<!-- Menu Code starts here -->
			<MAP NAME="menu">
				<AREA SHAPE="RECT" COORDS="28,37,96,22" HREF="index.php" TITLE="News">
				<AREA SHAPE="RECT" COORDS="28,54,97,37" HREF="about.php" TITLE="About the mod & Storyline">
				<AREA SHAPE="RECT" COORDS="28,70,153,55" HREF="downloads.php" TITLE="Downloads">
				<AREA SHAPE="RECT" COORDS="28,87,97,71" HREF="team.php" TITLE="Team & Staff Members">
				<AREA SHAPE="RECT" COORDS="28,104,127,87" HREF="gallery.php" TITLE="Gallery & Images">
				<AREA SHAPE="RECT" COORDS="28,121,168,104" HREF="journals.php" TITLE="Development Team's Journals">
				<AREA SHAPE="RECT" COORDS="28,138,97,122" HREF="help.php" TITLE="Help Page & Useful Information">
				<AREA SHAPE="RECT" COORDS="28,155,98,138" HREF="links.php" TITLE="Useful Links & Affiliates">
				<AREA SHAPE="RECT" COORDS="28,204,122,186" HREF="irc.php" TITLE="IRC Chat">
				<AREA SHAPE="RECT" COORDS="28,222,123,204" HREF="forum.php" TITLE="Community Forums">
				<AREA SHAPE="RECT" COORDS="43,263,130,325" HREF="http://sourceforge.net/projects/mechmod/" TITLE="Visit MechMod's SourceForge project page">
			</MAP>
			<img border="0" src="images/left.jpg" width="230" height="438" usemap=#menu>
			<!-- Menu Code ends here -->