<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="Author" content="grOOvy">
<meta name="keywords" content="MechMod, half-life, hl2, hl, mech, mod, modification, mechs, game, games, robots, strategy, action">
<meta name="Description" content="MechMod is a modification to Half-Life 2, a total conversion which brings you strategic and action-packed gameplay in a multiplayer environment!">